project:
  type: website

website:
  title: "Clara L. Hibbs"
  navbar:
    right:
      - icon: house-door-fill
        href: index.qmd
        text: Home
      - icon: hammer
        href: projects.qmd
        text: Projects
      - icon: journal-bookmark-fill
        href: publications.qmd
        text: Publications
      - icon: file-earmark-person
        href: cv.qmd
        text: CV

format:
  html:
    theme: styles.scss
    toc: true
    mainfont: DM Sans



